### ISSUE TITLE
finetune_demo不支持transformers v4.46.0

### ISSUE THREAD

**Issue by liuhongji2000** [THUDM/GLM-4#611]
### System Info / 系統信息

docker image：pytorch/pytorch:2.5.0-cuda12.4-cudnn9-devel
+ OS: Ubuntu 22.04
+ Memory: 512GB
+ Python: 3.11.10
+ CUDA Version:  12.4
+ GPU Driver: 550.107.02
+ GPU: NVIDIA A800 80GB PCIe * 4

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

```shell
python finetune.py  data/AdvertiseGen/  THUDM/glm-4-9b-chat  configs/lora.yaml 
```
错误信息、堆栈跟踪：
╭───────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────╮
│ /workspace/GLM-4/finetune_demo/finetune.py:472 in main                                                                               │
│                                                                                                                                      │
│   469 │   )                                                                                                                          │
│   470 │                                                                                                                              │
│   471 │   if auto_resume_from_checkpoint.upper() == "" or auto_resume_from_checkpoint is None:                                       │
│ ❱ 472 │   │   trainer.train()                                                                                                        │
│   473 │   else:                                                                                                                      │
│   474 │   │   output_dir = ft_config.training_args.output_dir                                                                        │
│   475 │   │   dirlist = os.listdir(output_dir)                                                                                       │
│                                                                                                                                      │
│ /opt/conda/lib/python3.11/site-packages/transformers/trainer.py:2122 in train                                                        │
│                                                                                                                                      │
│   2119 │   │   │   finally:                                                                                                          │
│   2120 │   │   │   │   hf_hub_utils.enable_progress_bars()                                                                           │
│   2121 │   │   else:                                                                                                                 │
│ ❱ 2122 │   │   │   return inner_training_loop(                                                                                       │
│   2123 │   │   │   │   args=args,                                                                                                    │
│   2124 │   │   │   │   resume_from_checkpoint=resume_from_checkpoint,                                                                │
│   2125 │   │   │   │   trial=trial,                                                                                                  │
│                                                                                                                                      │
│ /opt/conda/lib/python3.11/site-packages/transformers/trainer.py:2474 in _inner_training_loop                                         │
│                                                                                                                                      │
│   2471 │   │   │   │   │   │   self.control = self.callback_handler.on_step_begin(args, self.st                                      │
│   2472 │   │   │   │   │                                                                                                             │
│   2473 │   │   │   │   │   with self.accelerator.accumulate(model):                                                                  │
│ ❱ 2474 │   │   │   │   │   │   tr_loss_step = self.training_step(model, inputs, num_items_in_ba                                      │
│   2475 │   │   │   │   │                                                                                                             │
│   2476 │   │   │   │   │   if (                                                                                                      │
│   2477 │   │   │   │   │   │   args.logging_nan_inf_filter                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: Seq2SeqTrainer.training_step() takes 3 positional arguments but 4 were given

### Expected behavior / 期待表现

解决方案：
1. `finetune_demo/requirements.txt` 中添加 transformers<4.46.0
2. `finetune_demo/finetune.py` 和 `finetune_demo/finetune_vision.py` 中的 Seq2SeqTrainer.training_step 按照 [transformers.trainer.training_step](https://github.com/huggingface/transformers/blob/v4.46.0/src/transformers/trainer.py#L3543) 修改：
```python
    def training_step(self, model: nn.Module, inputs: dict[str, Any], num_items_in_batch=None) -> torch.Tensor:

        model.train()
        inputs = self._prepare_inputs(inputs)

        with self.compute_loss_context_manager():
            loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)

        if self.args.n_gpu > 1:
            loss = loss.mean()
        self.accelerator.backward(loss)
        detached_loss = loss.detach() / self.args.gradient_accumulation_steps
        del inputs
        torch.cuda.empty_cache()
        return detached_loss
```

**Comment by sixsixcoder** [comment]
感谢您的解决方案，transformers4.46中把模型中的可执行文件集成在transformers代码中，原先的模型权重已经不兼容4.46版本，您可以选择降低transformers版本<=4.45或者在huggingface下载最新的模型权重https://huggingface.co/THUDM/glm-4-9b-chat-hf

**Comment by ajsterling123** [comment]
`不行啊，最新的模型用transformers4.46还是有问题啊：
`glm4_finetune) ai@ai-MS-7D27:~/PycharmProjects/pythonProject/GLM-4-main/finetune_demo$ OMP_NUM_THREADS=1 torchrun --standalone --nnodes=1 --nproc_per_node=2  finetune.py  data  /home/ai/.cache/modelscope/hub/ZhipuAI/glm-4-9b-chat-hf  configs/lora.yaml
[rank0]: ╭────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────────────────────────────────────────────╮
[rank0]: │ /home/ai/PycharmProjects/pythonProject/GLM-4-main/finetune_demo/finetune.py:406 in main                                                                                                        │
[rank0]: │                                                                                                                                                                                                │
[rank0]: │   403 │   │   ),                                                                                                                                                                               │
[rank0]: │   404 ):                                                                                                                                                                                       │
[rank0]: │   405 │   ft_config = FinetuningConfig.from_file(config_file)                                                                                                                                  │
[rank0]: │ ❱ 406 │   tokenizer, model = load_tokenizer_and_model(model_dir, peft_config=ft_config.peft_co                                                                                                 │
[rank0]: │   407 │   data_manager = DataManager(data_dir, ft_config.data_config)                                                                                                                          │
[rank0]: │   408 │                                                                                                                                                                                        │
[rank0]: │   409 │   train_dataset = data_manager.get_dataset(                                                                                                                                            │
[rank0]: │                                                                                                                                                                                                │
[rank0]: │ /home/ai/PycharmProjects/pythonProject/GLM-4-main/finetune_demo/finetune.py:353 in load_tokenizer_and_model                                                                                    │
[rank0]: │                                                                                                                                                                                                │
[rank0]: │   350 ):                                                                                                                                                                                       │
[rank0]: │   351 │   tokenizer = AutoTokenizer.from_pretrained(model_dir, trust_remote_code=True)                                                                                                         │
[rank0]: │   352 │   if peft_config is not None:                                                                                                                                                          │
[rank0]: │ ❱ 353 │   │   model = AutoModelForCausalLM.from_pretrained(                                                                                                                                    │
[rank0]: │   354 │   │   │   model_dir,                                                                                                                                                                   │
[rank0]: │   355 │   │   │   trust_remote_code=True,                                                                                                                                                      │
[rank0]: │   356 │   │   │   empty_init=False,                                                                                                                                                            │
[rank0]: │                                                                                                                                                                                                │
[rank0]: │ /home/ai/anaconda3/envs/glm4_finetune/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py:564 in from_pretrained                                                             │
[rank0]: │                                                                                                                                                                                                │
[rank0]: │   561 │   │   │   )                                                                                                                                                                            │
[rank0]: │   562 │   │   elif type(config) in cls._model_mapping.keys():                                                                                                                                  │
[rank0]: │   563 │   │   │   model_class = _get_model_class(config, cls._model_mapping)                                                                                                                   │
[rank0]: │ ❱ 564 │   │   │   return model_class.from_pretrained(                                                                                                                                          │
[rank0]: │   565 │   │   │   │   pretrained_model_name_or_path, *model_args, config=config, **hub_kwargs,                                                                                                 │
[rank0]: │   566 │   │   │   )                                                                                                                                                                            │
[rank0]: │   567 │   │   raise ValueError(                                                                                                                                                                │
[rank0]: │                                                                                                                                                                                                │
[rank0]: │ /home/ai/anaconda3/envs/glm4_finetune/lib/python3.11/site-packages/transformers/modeling_utils.py:4096 in from_pretrained                                                                      │
[rank0]: │                                                                                                                                                                                                │
[rank0]: │   4093 │   │                                                                                                                                                                                   │
[rank0]: │   4094 │   │   with ContextManagers(init_contexts):                                                                                                                                            │
[rank0]: │   4095 │   │   │   # Let's make sure we don't run the init function of buffer modules                                                                                                          │
[rank0]: │ ❱ 4096 │   │   │   model = cls(config, *model_args, **model_kwargs)                                                                                                                            │
[rank0]: │   4097 │   │                                                                                                                                                                                   │
[rank0]: │   4098 │   │   # make sure we use the model's config since the __init__ call might have copied                                                                                                 │
[rank0]: │   4099 │   │   config = model.config                                                                                                                                                           │
[rank0]: ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
[rank0]: TypeError: GlmForCausalLM.__init__() got an unexpected keyword argument 'empty_init'
[rank0]:[W1028 21:09:06.090629288 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
W1028 21:09:06.562000 139893055230464 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 22789 closing signal SIGTERM
E1028 21:09:06.675000 139893055230464 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 22788) of binary: /home/ai/anaconda3/envs/glm4_finetune/bin/python
Traceback (most recent call last):
  File "/home/ai/anaconda3/envs/glm4_finetune/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ai/anaconda3/envs/glm4_finetune/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ai/anaconda3/envs/glm4_finetune/lib/python3.11/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/home/ai/anaconda3/envs/glm4_finetune/lib/python3.11/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/ai/anaconda3/envs/glm4_finetune/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ai/anaconda3/envs/glm4_finetune/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
finetune.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-28_21:09:06
  host      : ai-MS-7D27
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 22788)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
`

**Comment by zRzRzRzRzRzRzR** [comment]
需要使用4.46版本一下的transformers。4.46不支持
